import Head from 'next/head'
import Contato from '../components/Contato'
import Empresa from '../components/Empresa'
import Main from '../components/Main'
import Servicos from '../components/Servicos'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Canii - Obras e Reformas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main/>
      <Servicos/>
      <Empresa/>
      <Contato/>
    </div>
  )
}
